CREATE TYPE IF NOT EXISTS "CmsPageStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED');

CREATE TABLE IF NOT EXISTS "WebsitePage" (
  "pageKey" TEXT NOT NULL PRIMARY KEY,
  "path" TEXT NOT NULL UNIQUE,
  "title" TEXT NOT NULL,
  "content" TEXT NOT NULL DEFAULT '',
  "status" "CmsPageStatus" NOT NULL DEFAULT 'DRAFT',
  "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS "LegalPage" (
  "slug" TEXT NOT NULL PRIMARY KEY,
  "title" TEXT NOT NULL,
  "content" TEXT NOT NULL DEFAULT '',
  "status" "CmsPageStatus" NOT NULL DEFAULT 'PUBLISHED',
  "updatedAt" TIMESTAMP(3) NOT NULL
);
